### ISSUE TITLE
Email is not checked for uniqueness when creating user

### ISSUE THREAD

**Issue by lbighetti** [lbighetti/elixir-phoenix-realworld#31]
```elixir
Server: localhost:4000 (http)
Request: POST /users/login
** (exit) an exception was raised:
    ** (Ecto.MultipleResultsError) expected at most one result but got 2 in query:

from u in RealWorld.Accounts.User,
  where: u.email == ^"lbighetti9@gmail.com"

        (ecto) lib/ecto/repo/queryable.ex:71: Ecto.Repo.Queryable.one/4
        (real_world) lib/real_world/accounts/auth.ex:13: RealWorld.Accounts.Auth.find_user_and_check_password/1
        (real_world) lib/real_world_web/controllers/session_controller.ex:9: RealWorldWeb.SessionController.create/2
        (real_world) lib/real_world_web/controllers/session_controller.ex:1: RealWorldWeb.SessionController.action/2
        (real_world) lib/real_world_web/controllers/session_controller.ex:1: RealWorldWeb.SessionController.phoenix_controller_pipeline/2
        (real_world) lib/real_world_web/endpoint.ex:1: RealWorldWeb.Endpoint.instrument/4
        (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
        (real_world) lib/real_world_web/endpoint.ex:1: RealWorldWeb.Endpoint.plug_builder_call/2
        (real_world) lib/plug/debugger.ex:99: RealWorldWeb.Endpoint."call (overridable 3)"/2
        (real_world) lib/real_world_web/endpoint.ex:1: RealWorldWeb.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) /Users/leandro/ws/elixir-phoenix-realworld/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

**Comment by viniciusilveira** [comment]
I'd like to do this one.
